import React from "react";
import { cx, memberHandle } from "../../lib/helpers";
import { Icon } from "../ui/Icon";
import { Avatar } from "../ui/Avatar";
import { StatusDot } from "../ui/StatusDot";
import { MentionText } from "../ui/MentionText";
import { Chip } from "../ui/Chip";
import { STATUS, COMMANDS } from "../../lib/constants";

export function CronChip({ id  }: any) {
  return (
    <span className="inline-flex items-center gap-1 rounded-[5px] bg-[color-mix(in_oklab,var(--fg)_6%,transparent)] px-1.5 py-0.5 font-mono text-[10px] text-muted" title={'Generated by the “' + id + '” schedule'}>
      <Icon name="clock" size={10}/> cron · {id}
    </span>
  );
}

