import React from "react";
import { Icon } from "../ui/Icon";

/** The scheduler-origin marker on transcript messages (integrate-scheduler
 * chat spec): names the schedule when the name is known (runs-view context),
 * generic "Scheduled run" otherwise. */
export function SchedulerChip({ name  }: any) {
  return (
    <span className="inline-flex items-center gap-1 rounded-[5px] bg-[color-mix(in_oklab,var(--fg)_6%,transparent)] px-1.5 py-0.5 font-mono text-[10px] text-muted"
      title={name ? 'Generated by the “' + name + '” schedule' : 'Generated by a scheduled run'}>
      <Icon name="clock" size={10}/> {name ? 'scheduler · ' + name : 'Scheduled run'}
    </span>
  );
}
