/**
 * @vitest-environment jsdom
 */
// Scheduler-origin marker (integrate-scheduler 7.5): names the schedule when
// known (runs-view context), generic "Scheduled run" otherwise.
import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { SchedulerChip } from './SchedulerChip';

describe('components/chat/SchedulerChip', () => {
  it('names the schedule when the name is known', () => {
    render(<SchedulerChip name="morning-digest"/>);
    expect(screen.getByText('scheduler · morning-digest')).not.toBeNull();
    expect(screen.getByTitle('Generated by the “morning-digest” schedule')).not.toBeNull();
  });

  it('falls back to generic copy when no name is known', () => {
    render(<SchedulerChip name=""/>);
    expect(screen.getByText('Scheduled run')).not.toBeNull();
  });
});
